name: 'Get SSH key'
description: 'Get the SSH key from secrets'
inputs:
  server:
    description: 'Name of server'
    required: true
  test_secret:
    description: 'Test secret'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/script.sh
        ${{ github.action_path }}/script.sh ${{ inputs.server }}
      shell: bash
      env:
        TEST_SECRET: ${{ inputs.test_secret }}
