name: 'Get SSH key'
description: 'Get the SSH key from secrets'
inputs:
  server:
    description: 'Name of server'
    required: true
runs:
  using: 'composite'
  steps:
    - run: bash actions/get-ssh-key/script.sh ${{ inputs.server }}
      shell: bash
